Tell the memory size when cudaErrorMemoryAllocation occurred
Error message becomes as following:

    cupy.cuda.memory.OutOfMemoryError: out of memory to allocate XXXX bytes (total YYYY bytes)

instead of:

    cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory