Use modern dlpack interface in torch interoperability document
Because old interface is removed in numpy and sometime breaks compatibility of numpy and cupy
```
>>> t = torch.rand(10, 10)
>>> numpy.from_dlpack(to_dlpack(t))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'PyCapsule' has no attribute '__dlpack__'
```